name: Node.js CI

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: nodejs-backend/package-lock.json # Ensure this points to your lock file

    - name: Install dependencies
      working-directory: ./nodejs-backend # Correct path to your Node.js project
      run: npm install

    - name: Build with NodeJS
      working-directory: ./nodejs-backend
      run: npm run build

    - name: Test with Jest
      working-directory: ./nodejs-backend
      run: npm test
