name: MySQL Setup in GitHub Actions

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        # Optional: Used to wait for the service to be ready before proceeding.
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping -h"127.0.0.1" --silent; do
          sleep 1
        done

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: nodejs-backend/package-lock.json # Ensure this points to your lock file

    - name: Run tests
      run: |
        # Insert your build and test commands here
        # For example, a Java project might use Maven or Gradle:
        # mvn clean install
        # or
        # gradle test
        echo "Run your test commands that require MySQL here"
        
    - name: Additional commands if needed
      run: |
        echo "Perform additional steps"

