name: MySQL Setup in GitHub Actions

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: iot_plantation
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping -h"127.0.0.1" --silent; do
          sleep 1
        done

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: nodejs-backend/package-lock.json

    - name: Install dependencies
      working-directory: ./nodejs-backend
      run: npm install

    - name: Test with Jest
      working-directory: ./nodejs-backend
      run: npm test

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python-backend/requirements.txt

    - name: Run tests
      run: |
        pytest
